import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

component caclculateButton inherits Button {
    text: "caclculate";
    primary: true;
    height: 35px;
}

export component AppWindow inherits Window {

    in property <string> results: "";
    callback divide-income(string);

    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text { 
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }

        }

        Row {
            income := LineEdit {
                font-size: 16px;
                placeholder-text: "Enter your number";
                horizontal-alignment: center;
                height: 35px;
            }

        }

        Row {
            caclculateButton {
                clicked => {
                    divide-income(income.text)
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}

